AddTextEntryByHash(GetHashKey("a1"), "Ambulance Mercedes E Classe")
AddTextEntryByHash(GetHashKey("a2"), "Ambulance Mercedes sprinter 2018")
AddTextEntryByHash(GetHashKey("a3"), "Ambulance MAN TGE")
AddTextEntryByHash(GetHashKey("a4"), "Ambulance Touran rapid nieuw")
AddTextEntryByHash(GetHashKey("a5"), "Ambulance Mercedes Sprinter 2019")
AddTextEntryByHash(GetHashKey("a6"), "Ambulance Mercedes C meisen")
AddTextEntryByHash(GetHashKey("a7"), "Ambulance Volvo xc40 Ovdg")
AddTextEntryByHash(GetHashKey("a8"), "Ambulance Volvo Micu")
AddTextEntryByHash(GetHashKey("a9"), "Ambulance Motor")
AddTextEntryByHash(GetHashKey("amburapid"), "Ambulance Touran rapid oud")
AddTextEntryByHash(GetHashKey("Q7mmt"), "Ambulance Q7 mmt")
AddTextEntryByHash(GetHashKey("Traumahelikopter"), "Traumahelikopter")